name: gemini_multi_modal
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.2.4
  web_socket_client: ^0.1.5
# path: ^1.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.24.0
